### ISSUE TITLE
Yêu cầu - Thực hiện mô tả

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#11]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) **Nghị Văn BI**
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **01/07/2022**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **01/07/2022**
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) **DH Solution**

# ![yeu_cau_phat_sinh](https://img.shields.io/badge/Yêu%20cầu%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

```
 Thống nhất cách gởi ngay_yl và ngay_kq trên XML3, bổ sung các ràng buộc khi lập phiếu phẫu thuật và khi kết thúc hồ sơ.
```

# ![trien_khai](https://img.shields.io/badge/Qui%20trình%20thực%20hiện%20trên%20phần%20mềm%20–%20triển%20khai-:-blue?style=for-the-badge&logo=github)
 01/07/2022 hoàn thành --> gởi Nhóm HT test
# ![xu_ly_yeu_cau](https://img.shields.io/badge/Xử%20lý%20yêu%20cầu-:-blue?style=for-the-badge&logo=github)

```
https://github.com/dh-hos/Mo-ta-he-thong/blob/43b16cad8028d8db4397bede95709b1368923a30/Vinh%20-%20Mo%20ta%20cot%20%5Bdien_bien%5D%20%5Bhoi_chan%5D%20va%20%5Bphau_thuat%5D%20XML5%20-%2020220602.3.pdf
```

**Comment by ongtrieuhau** [comment]
#### Có 3 điểm cần xác định lại trong mô tả này:
##### Thứ nhất : trường hợp ngày vào viện nhỏ hơn 01/04/2022, không thấy điều kiện join qua bảng current.phauthuat 
![image](https://user-images.githubusercontent.com/58720300/176995568-67ba800d-d89a-4ee8-baa4-bded1833f802.png)
##### Thứ hai: trường hợp ngày vào lớn hơn 01/04/2022 và [MA_NHOM] = 8 hoặc [MA_NHOM] = 18 thì XML3. NGAY_KQ = current.chidinhcls. ngaygiokt => nhưng trong bảng chidinhcls không có cột này.
![image](https://user-images.githubusercontent.com/58720300/176995623-ff16188f-fbd5-44cc-9c20-fe849858dee5.png)
![image](https://user-images.githubusercontent.com/58720300/176995642-52aecf3c-0f6c-43aa-8e71-91dbd2dc1bb4.png)
##### Thứ ba: trường hợp cảnh báo, đề nghị kiểm tra theo NGAY_KQ (không kiểm theo 2 điều kiện chidinhcls.ngaykq và phauthuat.ngaygiokt) vì kiểm tra theo 2 điều kiện này sẽ không theo điều MA_NHOM, NGAY_VAO, KhoCLS theo cách tính phần trên
![image](https://user-images.githubusercontent.com/58720300/176995684-7c6d8ed4-cf74-4282-bd0d-635ae4eacc74.png)

**Comment by nghivanbi** [comment]
Thứ nhất: liên kết qua bảng phauthuat như trường hợp >= 01/04/2022. Cái hiện tại trong mô tả thể hiện phần lấy makho để xác định cls thuộc kho PT va TT.
Thứ hai: sai --> chỉnh lại phauthuat.ngaygiokt nha.
Thứ ba: xét cả chidinhcls.ngaykq và phauthuat.ngaygiokt nha, có cls phát sinh thuộc hồ sơ quyết toán là không cho in. Hiện tại thì chidinhcls.ngaykq không đủ cho trường hợp cls vừa có kết quả vừa có phiếu phẫu thuật.

**Comment by ongtrieuhau** [comment]
Đã cập nhật theo mô tả 

- [Printer v3.22.0703.1](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)
- [Services v3.22.0703.1](https://github.com/dh-hos/dhg.hospitalservices/blob/main/Deploy_Tools/CHANGELOG.md)
- [Admin v3.22.0703.1](https://github.com/dh-hos/dhg.hospitaladmin/blob/main/Deploy_Tools/CHANGELOG.md)

**Comment by le-an-87** [comment]
Đã test xuất XML từ Reports và Admin dữ liệu xuất xml3.ngayyl, xml3.ngaykq, xml5 đúng theo mô tả.
Prescription và Treatment đã có cảnh báo ngày giờ kết quả lớn hơn ngày giờ ra viện và không cho kết thúc.
Dữ liệu test: an_test_xml

**Comment by nghivanbi** [comment]
Cập nhật mô tả: trường hợp toa vật tư khi gởi XML3: https://github.com/dh-hos/Mo-ta-he-thong/blob/main/Vinh%20-%20Mo%20ta%20cot%20%5Bdien_bien%5D%20%5Bhoi_chan%5D%20va%20%5Bphau_thuat%5D%20XML5%20-%2020220602.4.pdf

**Comment by nghivanbi** [comment]
Chỗ toa vật tư này đã cập nhật chưa @lqbinh1987 ?

**Comment by lqbinh1987** [comment]
Cập nhật ok rồi he anh @nghivanbi .
