### ISSUE TITLE
Yêu cầu - Mô tả thực hiện Thông tư 36/2021/TT-BYT

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#12]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **16/08/2022**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **17/08/2022**
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) **DH Solution**

# ![yeu_cau_phat_sinh](https://img.shields.io/badge/Yêu%20cầu%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

```
```

# ![trien_khai](https://img.shields.io/badge/Qui%20trình%20thực%20hiện%20trên%20phần%20mềm%20–%20triển%20khai-:-blue?style=for-the-badge&logo=github)

# ![xu_ly_yeu_cau](https://img.shields.io/badge/Xử%20lý%20yêu%20cầu-:-blue?style=for-the-badge&logo=github)

Thực hiện Thông tư 36/2021/TT-BYT
[3153.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/9349064/3153.pdf)
https://luatvietnam.vn/y-te/thong-tu-36-2021-tt-byt-bo-y-te-215312-d1.html

**Comment by nghivanbi** [comment]
- Góp ý mô tả.
- Hạn hết ngày: 19/08/2022


[Vinh - Mo ta cap phat thuoc nguoi benh Lao theo TT36 va CV3153 - 17-08-2022.docx](https://github.com/dh-hos/Mo-ta-he-thong/files/9366831/Vinh.-.Mo.ta.cap.phat.thuoc.nguoi.benh.Lao.theo.TT36.va.CV3153.-.17-08-2022.docx)

**Comment by nghivanbi** [comment]
Thực hiện mô tả: 
[Vinh - Mo ta cap phat thuoc nguoi benh Lao theo TT36 va CV3153 - 17-08-2022.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/9553155/Vinh.-.Mo.ta.cap.phat.thuoc.nguoi.benh.Lao.theo.TT36.va.CV3153.-.17-08-2022.pdf)

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.0914.2](http://www.fsend.vn/download/b5HznkroNJZ8HGekJXTCYblCvpq1Nm5L)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0914.1](http://www.fsend.vn/download/WlcHYqsP74c0mPJ5ZDrjCYxz9LHHPfTE)

**Comment by vuongdh** [comment]
Cập nhật:
![image](https://user-images.githubusercontent.com/32563776/190116533-c2014d03-6691-4e5f-b416-db4d317e855c.png)

Treatment: [v1.22.0914.1](http://www.fsend.vn/download/h8_xCp-jFZHV_K_le7UTulJJ1l7-HqNg)

**Comment by vinh-dh** [comment]
[Reports 15/09/2022](https://www.fshare.vn/file/UBQFQ2UTBRNQ)

**Comment by ongtrieuhau** [comment]
Printer : [3.22.0924.4](https://github.com/dh-hos/dhg.hospitalprinter/commit/d07b54b8f84cb13f8b60359c2cca5decb358ab1d)

**Comment by ongtrieuhau** [comment]
Admin : [3.22.0924.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/dfd31c93a82b8d5c1ccb1e53b18322b4fcd7e1ed)

**Comment by ongtrieuhau** [comment]
Services: [3.22.0924.1](https://github.com/dh-hos/dhg.hospitalservices/commit/335ba9028090516462ba48b3311b1eb960aec302)

**Comment by chauthanhtra** [comment]
1.	Prescription 
-	Khi in phiếu không cập nhật được chuỗi psdangky.kqcdoan = “Cấp thuốc theo Giấy Xác nhận điều trị nội trú của cơ sở khám bệnh, chữa bệnh: <ten_co_so_kcb>, ngày cấp: <ngaychungnhan_lao>”
-	Khi Printer in rồi có cập nhật psdangky.kqcdoan đúng sau đó Prescription bấm in lại thì bị cập nhật lại sai psdangky.kqcdoan
![ảnh](https://user-images.githubusercontent.com/97272332/192440304-abdeba82-c732-4d74-8056-ac0e78f5f823.png)

2.	Reports 
-	Bệnh nhân trái tuyến được hưởng cùng tuyến có psdangky.tuyenxml = 1 thì mã hoá sai ma_lydo_vvien
![ảnh](https://user-images.githubusercontent.com/97272332/192440520-f8a5375f-2ffd-4ce9-b69d-915d6f6cffdf.png)
![ảnh](https://user-images.githubusercontent.com/97272332/192440573-9c712d51-c4d2-4c79-afd9-559d02931a76.png)
![ảnh](https://user-images.githubusercontent.com/97272332/192440604-180e7bf5-5881-48bd-b74d-b2ce5c661569.png)

**Comment by le-an-87** [comment]
1. Đề xuất thêm chức năng cho điều chỉnh từ bệnh bình thường sang bệnh Lao và ngược lại.

2. Trường hợp bệnh nhân có mã bệnh kèm theo thì trường 13 XML sẽ có mã bệnh kèm theo nhưng theo cv thì không có yêu cầu ghép tên bệnh đối với bệnh nhân khám Lao. trong mô tả cũng không có yêu cầu ghép
![image](https://user-images.githubusercontent.com/96155021/192472669-d8450ccb-56f5-4761-b961-c594a60840fb.png)
![image](https://user-images.githubusercontent.com/96155021/192473037-02a12488-0743-4a6f-a79c-73f9fcfc6c2e.png)

3. Khi in giấy Xác nhận điều trị Lao. hiện tại Tất cả bệnh nhân điều in được phiếu này
 -> Đề xuất: chỉ những bệnh nhân có check Bệnh nhân Lao mới cấp được phiếu chứng nhận Lao và ghi nhận ngày giờ cấp để dễ quản lý.

**Comment by le-an-87** [comment]
4. Đề xuất thêm dấu hiệu nhận biết bệnh nhân là bệnh lao hay bệnh bình thường giống như trường hợp bệnh cấp cứu. để người dùng dễ phân biệt.

**Comment by nghivanbi** [comment]
cái này em phần hồi vô từng module dùm anh nha để dễ theo dõi hoàn thành hay chưa á Ân.

**Comment by ongtrieuhau** [comment]
Khi gửi hoặc xem XML gửi BHXH sẽ cập nhật lại kqcdoan với toàn bộ chẩn đoán của bệnh nhân đó, như vậy nó sẽ sai với mô tả này. Vì vậy phải cập nhật 2 module này để hỗ trợ thêm, khi kqcdoan bắt đầu bằng "**CẤP THUỐC THEO GIẤY XÁC NHẬN ĐIỀU**" sẽ không cập nhật lại trường kqcdoan trong psdangky. Cập nhật hỗ trợ tại đây:
- Admin: [3.22.0929.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/696b2f9e35a25fe8feb2778aea89df99d0b699b8)
- Services: [3.22.0929.1](https://github.com/dh-hos/dhg.hospitalservices/commit/a2e7f7a2883c1f012f6bdf2408d4558b5af3660f)

**Comment by vinh-dh** [comment]
Bổ sung mô tả từ [Công văn 7382/BYT-BH ngày 21/12/2022](https://github.com/dh-hos/CongVan-QuyDinh-DeNghi/issues/1)
[Vinh - Mo ta cap phat thuoc nguoi benh Lao theo TT36 va CV3153; CV7382 - 16-01-2023.docx](https://github.com/dh-hos/Mo-ta-he-thong/files/10424019/Vinh.-.Mo.ta.cap.phat.thuoc.nguoi.benh.Lao.theo.TT36.va.CV3153.CV7382.-.16-01-2023.docx)

@nghivanbi xem ok thì duyệt nhe!

**Comment by ongtrieuhau-dh** [comment]
Đóng lại do cái https://github.com/dh-hos/CongVan-QuyDinh-DeNghi/issues/1 đã close
