### ISSUE TITLE
Yêu cầu - Bổ sung ghi nhận email vào thông tin bệnh nhân hỗ trợ LIS

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#13]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **24/08/2022**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **25/08/2022**
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) **DH Solution**

# ![yeu_cau_phat_sinh](https://img.shields.io/badge/Yêu%20cầu%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

```
```

# ![trien_khai](https://img.shields.io/badge/Qui%20trình%20thực%20hiện%20trên%20phần%20mềm%20–%20triển%20khai-:-blue?style=for-the-badge&logo=github)

# ![xu_ly_yeu_cau](https://img.shields.io/badge/Xử%20lý%20yêu%20cầu-:-blue?style=for-the-badge&logo=github)
[Bi - Mo ta bo sung ghi nhan email vao thong tin benh nhan.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/9411880/Bi.-.Mo.ta.bo.sung.ghi.nhan.email.vao.thong.tin.benh.nhan.pdf)
```


```

**Comment by nghivanbi** [comment]
Cập nhật:
Register : [v3.22.08.23.1](http://www.fsend.vn/download/kdLuP8drjRaHiH3RRhGmjG7KfuRpRTAJ)

**Comment by vinh-dh** [comment]
Đã có script
