### ISSUE TITLE
Yêu cầu - Mở rộng chức năng quản lý hồ sơ lưu trữ cho bệnh ngoại trú

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#14]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **26/10/2022**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Hạn%20Góp%20ý-:-blue?style=plastic&logo=github) **26/10/2022**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **28/10/2022**
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) **79029 [BV Quận 12] **

# ![yeu_cau_phat_sinh](https://img.shields.io/badge/Yêu%20cầu%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

[Bi - Mo ta bo sung so luu tru cho benh nhan ngoai tru_v2.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/9867460/Bi.-.Mo.ta.bo.sung.so.luu.tru.cho.benh.nhan.ngoai.tru_v2.pdf)

```
```

**Comment by nghivanbi** [comment]
Thực hiện theo mô tả :
[Bi - Mo ta bo sung so luu tru cho benh nhan ngoai tru_v3.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/9885252/Bi.-.Mo.ta.bo.sung.so.luu.tru.cho.benh.nhan.ngoai.tru_v3.pdf)

**Comment by vinh-dh** [comment]
[Reports 04/11/2022](https://www.fshare.vn/file/7GFHTFC6MCI9)

**Comment by nghivanbi** [comment]
[Bi - Mo ta bo sung so luu tru cho benh nhan ngoai tru_v4.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/9977826/Bi.-.Mo.ta.bo.sung.so.luu.tru.cho.benh.nhan.ngoai.tru_v4.pdf)
- Vinh cập nhật lại bỏ xét điều kiện psdangky.dain nha.

**Comment by vinh-dh** [comment]
[SetupHospitalReport20221110](https://www.fshare.vn/file/NXHAQLHCXG7A)

**Comment by lqbinh1987** [comment]
Chưa được anh @vinh-dh  ơi, như BN này chưa in, sổ cấp số rồi, nhưng sổ lưu trữ không load lên được.
![image](https://user-images.githubusercontent.com/99630883/201051998-58203e73-acea-41e3-a556-faaa6bfed7a2.png)
![image](https://user-images.githubusercontent.com/99630883/201052041-d97e7995-d9cf-4128-8e4d-0726f67a3f38.png)

**Comment by vinh-dh** [comment]
Điều kiện ra viện là ngayinphieu. Cột này không có giá trị thì sổ không load được là phải rồi. Mô tả cập nhật loại bỏ dain = 1 thì khi cấp phát số lưu trữ nên cấp phát ngayinphieu (nếu nó đang null) luôn nhé @nghivanbi.

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.1111.1](http://www.fsend.vn/download/ICKczJpR9RWYIfq1lMXEDeB9zFmtNA5F)

**Comment by vinh-dh** [comment]
Cập nhật sổ khám bệnh: [SetupHospitalReport20221111](https://www.fshare.vn/file/W85PVYYPB6OK)
