### ISSUE TITLE
Yêu cầu - Thực hiện quyết định 04/2022/TT-BYT

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#15]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **28/10/2022**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **31/10/2022**
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) **Tất cả**

# ![yeu_cau_phat_sinh](https://img.shields.io/badge/Yêu%20cầu%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

```
```

# ![trien_khai](https://img.shields.io/badge/Qui%20trình%20thực%20hiện%20trên%20phần%20mềm%20–%20triển%20khai-:-blue?style=for-the-badge&logo=github)

# ![xu_ly_yeu_cau](https://img.shields.io/badge/Xử%20lý%20yêu%20cầu-:-blue?style=for-the-badge&logo=github)

[Bi - Mo ta bo sung sinh ma toa thuoc theo quyet dinh 04.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/9885285/Bi.-.Mo.ta.bo.sung.sinh.ma.toa.thuoc.theo.quyet.dinh.04.pdf)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.1031.1](http://www.fsend.vn/download/sWvCdphpBKCNmWbS8DH9D0GdkzIPEt83)

**Comment by nghivanbi** [comment]
Fix lỗi xem toa: [v3.22.1031.2](http://www.fsend.vn/download/6L52ll_YSyyNI6KW01S4FvNIJh3ipBa-)

**Comment by le-an-87** [comment]
đã cập nhật!

**Comment by vuongdh** [comment]
@le-an-87 Cập nhật [20221103v1](http://www.fsend.vn/download/jLlK94rBy-2jtZ90zHW5cctFvBGaYs0m)

**Comment by vuongdh** [comment]
@le-an-87 Cập nhật hiển thị mã đơn thuốc [Treat4.20221110v2](http://www.fsend.vn/download/nQ3ylMkuz8LZJ7p1kEMiAi_SvWG2N5sB)

**Comment by le-an-87** [comment]
Hiện tại toa thuốc còn thiếu 3 trường này nhe anh!
Ngaysinh: ghi ngày tháng năm sinh
Số đt liên hệ: của người bệnh hoặc người nhà người bệnh
   -> hiện tại đã có số đt người bệnh.
CCCD của người lãnh thuốc Hướng thần và Nghiện
![image](https://user-images.githubusercontent.com/96155021/201571318-72af43d3-ac8f-49b5-8f06-70f90f29ace7.png)
![image](https://user-images.githubusercontent.com/96155021/201571328-0d2c3348-915a-41af-ac24-e887e1bed40c.png)

**Comment by vuongdh** [comment]
@le-an-87 Bản cập nhật [Treat4.20221115v1](http://www.fsend.vn/download/jv22bzujxoJ5bIIZP0MGuqp96Y8FAUEa)
