### ISSUE TITLE
Yêu cầu - Mô tả và thực hiện hỗ trợ gởi hồ sơ các bệnh án điều trị dưới 4h

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#18]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![hoan_thanh](https://img.shields.io/badge/Hoàn%20thành-:-blue?style=plastic&logo=github)  **27/10/2022**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
[3788_BYT_Mã hoa hinh thuc KCB.pdf](https://github.com/dh-hos/dhg.hospitalservices/files/9865043/3788_BYT_Ma.hoa.hinh.thuc.KCB.pdf)

```

**Comment by nghivanbi** [comment]
https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/Hau-Mo-ta-XML-Noi-tru-4h-3788_BYT-BH.md

Thực hiện theo mô tả: hoàn thành 07/11/2022

**Comment by ongtrieuhau** [comment]
Cập nhật:
- Admin: [3.22.1107.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/58e4309b5d4fc6649a2e5a25e260baf67f935eea)
- Services: [3.22.1107.1](https://github.com/dh-hos/dhg.hospitalservices/commit/badc220708f25ce8fa32bd0258a7a6c5cdfd8744)

**Comment by vinh-dh** [comment]
[SetupHospitalReport20221107v1](https://www.fshare.vn/file/F42P1TPSLEUU)

**Comment by le-an-87** [comment]
1. Module admin và service đã cập nhật xong!

2. Reports khi xuất xml 4210 thì không có dữ liệu
![image](https://user-images.githubusercontent.com/96155021/200466871-cc946a7d-bc69-4613-a73f-4b668bc4e96a.png)
![image](https://user-images.githubusercontent.com/96155021/200466952-656cd967-f6c5-41c8-8699-fdccd47e43d3.png)

**Comment by vinh-dh** [comment]
@le-an-87 gửi anh tên data để a kiểm tra.

**Comment by le-an-87** [comment]
data: an_lapvo_bnlao
dữ liệu đó anh @vinh-dh ơi!

**Comment by vinh-dh** [comment]
[SetupHospitalReport20221108](https://www.fshare.vn/file/9XPGVRW14578)

**Comment by le-an-87** [comment]
Reports ok rồi anh ơi!

**Comment by vuongdh** [comment]
@le-an-87  Treatment cập nhật cảnh báo xuất viện khi bệnh nhân **có sử dụng tiền giường và tổng thời gian điều trị <=4 giờ**
[Treat4.20221110v1](http://www.fsend.vn/download/K5TljCQJgm9ir1oy47XMPLvcsFBuc571)

**Comment by le-an-87** [comment]
Treatment đã hỗ trợ cảnh báo có cls ngày giường khi bệnh cho ra viện dưới 4h!
![image](https://user-images.githubusercontent.com/96155021/201013501-094eaa62-83c9-4e86-8078-708ef8e11a26.png)
