### ISSUE TITLE
Yêu cầu - Ghi nhận thêm trường BHXH cho người bệnh

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#20]
[Bi - Mo ta bo sung so ghi nhan thong tin BHXH cho benh nhan.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/10264449/Bi.-.Mo.ta.bo.sung.so.ghi.nhan.thong.tin.BHXH.cho.benh.nhan.pdf)

**Comment by nghivanbi** [comment]
Cập nhật: 
Register: [v3.22.1222.1](http://www.fsend.vn/download/9VJ9XpEiznDCv5DMsUbKAyq5GeTvV7FA)

**Comment by vinh-dh** [comment]
[SetupHospitalReport20221222](https://www.fshare.vn/file/V3I2HY3AXIIS)

**Comment by vuongdh** [comment]
Cập nhật treatment
 [Treat4.20221223v1](http://www.fsend.vn/download/s2jhbRTYuSdyJ25z-dZIrW9Aou6ZVRJP)

**Comment by nghivanbi** [comment]
Ân check cập nhật ok hết theo mô tả --> Close nhé.

**Comment by le-an-87** [comment]
Đã cập nhật theo mô tả!
