### ISSUE TITLE
Yêu cầu - Cập nhật mã cơ sở khám chữa bệnh mới 

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#21]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **26/12/2022**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **28/12/2022**
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) **DH Solution**

# ![yeu_cau_phat_sinh](https://img.shields.io/badge/Yêu%20cầu%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

1- [SYT- VB cap Ma BHYT -77154- PKDK Binh An-co so 2.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/10301259/SYT-.VB.cap.Ma.BHYT.-77154-.PKDK.Binh.An-co.so.2.pdf)
2- Theo thông tin sau:
SỞ Y TẾ TP. CẦN THƠ
 Mã BV: 92137 
 Trung tâm y tế quận Ninh Kiều
 Địa chỉ: 209 Nguyễn Trãi,phường Thới Bình,quận Ninh Kiều,thành phố Cần Thơ
 Điện thoại: 02923760466

# ![xu_ly_yeu_cau](https://img.shields.io/badge/Xử%20lý%20yêu%20cầu-:-blue?style=for-the-badge&logo=github)

1. Thực hiện cấp License theo mã phòng khám.
2.  Fees: mở thêm kết nối hóa đơn điện tử với VNPT (đối với 77154)
3.  Lab: liên kết xét nghiệm Minh Dương (đối với 77154)
4.  Các module cập nhật License mới.

**Comment by ongtrieuhau** [comment]
Cập nhật [License.dll](https://github.com/dh-hos/oLibraries/commit/2212278a0946d46478c0a3eefc9973cc48fcd2ea)

**Comment by ongtrieuhau** [comment]
> 2. Fees: mở thêm kết nối hóa đơn điện tử với VNPT (đối với 77154)

`{"AtRow":63,"mabvbh":"77154","DateExpires":"2023-01-31","UseHddtBy":"Vnpt","Trial":""}
=====DECODE=====
U2FsdGVkX1/URa3/DqZZKaY1xr0XSWKBqUah+g8z0ay4MvwA3ycq23wWj+oJOEAzJmJEgFJfid5Y6mbA/cMNL19AmS2kOl8xZkxZZq9/dc5KG1iN0iEfIzYFA4ENBT2lW/peXwdC++tiUxvg+TQGDA==`

**Comment by ongtrieuhau** [comment]
Bổ sung mã [92137](https://github.com/dh-hos/oLibraries/commit/28a34e3b190104d0ef61130efdc4e1ccea3449c0)

**Comment by ongtrieuhau** [comment]
Admin [3.22.1226.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/6ff56eec6e99c7dbde93b22f6541b6896c13ae65)
Fees [3.22.1226.1](https://github.com/dh-hos/dhg.hospitalfees/commit/8319905e25802fef1e229f181c298d74855af4be)
Printer [3.22.1226.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/9571cc6c238f12406a132506268d7d9d05ba6b4e)

**Comment by nghivanbi** [comment]
@lqbinh1987 theo dõi issues này nhé.

**Comment by nghivanbi** [comment]
Register: [v3.22.12.26.1](http://www.fsend.vn/download/Om1MEFxrIovFTatcwGI99tQcW-_Td-Z6)

**Comment by lqbinh1987** [comment]
Anh @vinh-dh ơi build mấy cái của anh theo 2 mã BV trên dùm em.

**Comment by vinh-dh** [comment]
@nghivanbi cập nhật Reg hỗ trợ kết nối XN 77154: [Liên kết xét nghiệm Minh Dương (đối với 77154)](https://github.com/dh-hos/oLibraries/commit/16b8daa1de10b3c05df5b5315f079e3cde2c425b)

**Comment by vinh-dh** [comment]
- [HospitalLaboratorySetup20221227](http://192.168.10.79:8090/Labotory/HospitalLaboratorySetup20221227.zip)
- [HospitalDiagnoseSetup20221227](http://192.168.10.79:8090/Diagnose/HospitalDiagnoseSetup20221227.zip)
- [SetupHospitalReport20221227](http://192.168.10.79:8090/Reports/SetupHospitalReport20221227.zip)

**Comment by vinh-dh** [comment]
Thử lại nhé @nghivanbi [Liên kết xét nghiệm Minh Dương (đối với 77154)](https://github.com/dh-hos/oLibraries/commit/1616999b38aa7cce54681320ed00f3bf2febe108)

**Comment by nghivanbi** [comment]
Register: [v3.22.12.27.1](http://www.fsend.vn/download/H1LYjLY40FV8nZR2csO9NrupnvVUKuXf)
