### ISSUE TITLE
[Cập nhật mô tả] - Ghi nhận MỨC HƯỞNG chi phí BHYT của người bệnh  khi áp NGÀY MIỄN CÙNG CHI TRẢ

### ISSUE THREAD

**Issue by vinh-dh** [dh-hos/Mo-ta-he-thong#22]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) [vinh-dh](https://github.com/vinh-dh)
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **Ngày cập nhật: 17/02/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) 
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) 

Chi tiết mô tả bổ sung: [Vinh - Mo ta ghi nhan muc huong 100 khi ap ngay mien chi tra - 27-02-2020 - v3.docx](https://github.com/dh-hos/Mo-ta-he-thong/files/10762345/Vinh.-.Mo.ta.ghi.nhan.muc.huong.100.khi.ap.ngay.mien.chi.tra.-.27-02-2020.-.v3.docx)

Bổ sung mô tả theo yêu cầu: [Yêu cầu - thực hiện miễn giảm theo thẻ BHYT](https://github.com/dh-hos/dhg.hosptaltreatment/issues/74)

**Comment by le-an-87** [comment]
Mô tả này em thấy chưa áp dụng được cho bệnh nhân nằm viện 2 năm đó anh.
ví dụ:
Trường hợp bệnh nằm viện năm 2022 có giấy chứng nhận miễn
-> giảm hết năm 2022
bệnh nằm viện đến năm 2023 mới ra viện ( trường hợp không tách thẻ)
-> năm 2023 không được hưởng giấy chứng nhận miễn

**Comment by vinh-dh** [comment]
Bổ sung mô tả `ngaymienct_ketthuc`: [Vinh - Mo ta ghi nhan muc huong 100 khi ap ngay mien chi tra - 27-02-2020 - v4.docx](https://github.com/dh-hos/Mo-ta-he-thong/files/10788804/Vinh.-.Mo.ta.ghi.nhan.muc.huong.100.khi.ap.ngay.mien.chi.tra.-.27-02-2020.-.v4.docx)

**Comment by vinh-dh** [comment]
> Bổ sung mô tả `ngaymienct_ketthuc`: [Vinh - Mo ta ghi nhan muc huong 100 khi ap ngay mien chi tra - 27-02-2020 - v4.docx](https://github.com/dh-hos/Mo-ta-he-thong/files/10788804/Vinh.-.Mo.ta.ghi.nhan.muc.huong.100.khi.ap.ngay.mien.chi.tra.-.27-02-2020.-.v4.docx)

@nghivanbi cái này có làm không? Không làm thì hủy nhe!

**Comment by ongtrieuhau** [comment]
Nhờ @le-an-87 @lqbinh1987  cho xin dữ liệu phần mô tả này nhé

**Comment by le-an-87** [comment]
Tên data: an_motahethong_issues_22
MABN: 2022003042 - maba: 019046
madv: 01
ngày vv: 15/11/2022  - ngày ra: 06/01/2023  - Tháng ra viện: 01/2023
ngày miễn cùng chi trả: 02/11/2022

**Comment by ongtrieuhau** [comment]
Cập nhật Fees [3.23.0412.1](https://github.com/dh-hos/dhg.hospitalfees/commit/3426e44f28310dfe8540aeff0f9fb4e07580d047)

**Comment by nghivanbi** [comment]
@le-an-87 test cái này so với Treat, ok gởi Ung Bướu cập nhật nha.

**Comment by le-an-87** [comment]
ok anh

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/231381849-c18e0f90-5b9d-4536-be49-fd376197acdd.png)
Fees vào nội trú bị lỗi anh @ongtrieuhau ơi

**Comment by ongtrieuhau** [comment]
Thiếu cấu trúc rồi. Chạy cập nhật cấu trúc hết nhé.

**Comment by le-an-87** [comment]
cái này hình như thiếu cấu trúc rồi mấy anh ơi!
Hiện tại Reports và Treatment có làm theo mô tả này chưa anh @vuongdh  anh @vinh-dh

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/231394473-d04a0c4b-635b-4c53-9316-91ea7359921d.png)
chưa có cript cấu trúc mới anh ơi

**Comment by nghivanbi** [comment]
@vinh-dh cập nhật cấu trúc theo mô tả và cập nhật report.
@vuongdh cập nhật treat nhé.

**Comment by le-an-87** [comment]
chổ này vào bị lỗi thiếu cấu trúc https://github.com/dh-hos/Mo-ta-he-thong/issues/22
chờ cập nhật xong mới kiểm tra đc nhe anh!

**Comment by vinh-dh** [comment]
![image](https://user-images.githubusercontent.com/112069710/231695871-7aa578b0-dd35-467f-a518-fba833f7c6ad.png)

Local:
- [SetupHospitalReport20230413](http://192.168.10.79:8090/Reports/SetupHospitalReport20230413.zip)

Fshare:
- [SetupHospitalReport20230413](https://www.fshare.vn/file/5D7MBBGZENV7)

**Comment by le-an-87** [comment]
Module Fees và Reports đã hỗ trợ được trường hợp tách thẻ!
Trường hợp không tách thẻ nhưng nhập ngày kết thúc miễn hiện tại chưa bổ sung chức năng nhập ngày kết thúc miễn!
Điều chỉnh trực tiếp dữ liệu thì Fees và Reports vẫn chưa áp dụng đc theo ngày kết thúc
![image](https://user-images.githubusercontent.com/96155021/231943188-beed986d-019e-46af-8546-7cbcebe0b4c4.png)

**Comment by vuongdh** [comment]
@le-an-87 Cập nhật:
- Chỉnh đối tượng: thêm chức năng cập nhật ngày kết thúc miễn chi trả
- Thông tin thẻ BHYT 2: thêm chức năng cập nhật ngày kết thúc miễn chi trả
[Link cập nhật](http://www.fsend.vn/download/AhsHnQxqqlPSvtK2GJoV8AvlThjGsjJb)

**Comment by le-an-87** [comment]
Em gửi thông tin để mấy anh có test thử thì test nhe!
trường hợp bệnh có thời hạn sử dụng thẻ từ năm 2022 đến năm 2023 và nhập chứng nhận miễn
tên data: an_chungnhanmien_mota_22
maba: 2022016734
khoa: 11
thời hạn miễn trong năm 2022

![image](https://user-images.githubusercontent.com/96155021/232004297-13e502d8-1ef7-48cf-a914-50e32530545e.png)

**Comment by le-an-87** [comment]
Dữ liệu bệnh nhân này nhập:
ngày kết thúc miễn 31/12/2022
![image](https://user-images.githubusercontent.com/96155021/232378006-baf40f36-64c9-49d3-8e54-39f9a4a04b15.png)
các chi phí sau năm 2022 không được hưởng miễn cùng chi trả
![image](https://user-images.githubusercontent.com/96155021/232378423-d11a95d1-660f-4baf-9e58-fa8118112c2a.png)
-> mà phần mềm hiện tại đều được hưởng miễn chi trả anh!

**Comment by ongtrieuhau** [comment]
Do bệnh nhân này đâu thuộc dạng thu % đâu @le-an-87 
![image](https://user-images.githubusercontent.com/58720300/232394276-f0bd1cbc-8952-4549-a626-d01307d0741b.png)

**Comment by ongtrieuhau** [comment]
Cái này dứt điểm được chưa @le-an-87 ?

**Comment by le-an-87** [comment]
chổ này theo mô tả đó thì chưa áp dụng đc. trường hợp % thu bằng 0 thì anh @vuongdh giải quyết giùm em nhe!
khi check chứng nhận miễn thì dữ liệu ghi nhận thế nào mới đúng?
trường hợp này trước giờ em thấy điều ghi nhận =0 hết!

**Comment by vuongdh** [comment]
@le-an-87 Cái này thể hiện chi phí sai hay sao em?
Chứng nhận miễn thì ghi nhận miễn: từ ngày đến ngày thôi, chi phí thì ghi nhận như bình thường. Còn khi nào tính chi phí (6556,...) thì tính theo mô tả

**Comment by le-an-87** [comment]
alo anh @vuongdh 
khi check chứng nhận miễn thì dữ liệu trường ptthu anh ghi nhận thế nào vậy anh?
ghi theo mã quyền lợi hay sao anh?
ví dụ như thẻ GD4 thu 20% thì khi check chứng nhận miễn anh ghi nhận trường ptthu = mấy

**Comment by le-an-87** [comment]
anh xác nhận giùm em chổ pthu ghi nhận thế nào anh. cái này không có mô tả cụ thể nên không xác định đc đúng hay sai? còn ghi nhận bình thường em cũng không biết thế nào là bình thường.

**Comment by vuongdh** [comment]
@le-an-87 liên quan nhiều mô tả lắm, để anh nhờ Bi và Vinh gửi lại cho em
@nghivanbi gửi lại cho @le-an-87 mô tả ghi nhận ptthu dùm hén
@vinh-dh gửi cho @le-an-87 mô tả cách tính miễn cùng chi trả mới và cũ dùm hén
