### ISSUE TITLE
Yêu cầu - Mô tả Quyết định 130

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#23]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
- ![nguoi_lap](https://img.shields.io/badge/Người%20thực%20hiện-:-blue?style=plastic&logo=github) **Nguyễn Viết Vinh**
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **20/02/2023**
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) **DH Solution**

# ![yeu_cau_phat_sinh](https://img.shields.io/badge/Yêu%20cầu%20phát%20sinh-:-blue?style=for-the-badge&logo=github)
- Mô tả thực hiện quyết định.
- Mô tả theo phương án lưu trữ dữ liệu theo cấu trúc XML (để đồng nhất khâu hồ sơ XML).
[130Q .signed.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/10779722/130Q.signed.pdf)
[20230118_Chuan du lieu dau ra_FINAL.xlsx](https://github.com/dh-hos/Mo-ta-he-thong/files/10779723/20230118_Chuan.du.lieu.dau.ra_FINAL.xlsx)

**Comment by vinh-dh** [comment]
[Vinh - Mo ta XML Quyet Dinh 130 - 27-02-2023.docx](https://github.com/dh-hos/Mo-ta-he-thong/files/11120348/Vinh.-.Mo.ta.XML.Quyet.Dinh.130.-.27-02-2023.docx)

**Comment by nghivanbi** [comment]
Tất cả góp ý mô tả. Hạn góp ý  07/04/2023 nhé.

**Comment by lqbinh1987** [comment]
Nhờ mấy anh cho em biết tiến độ của QĐ này giúp em, hiện giờ nhiều BV hỏi để có thể chạy Demo được chưa?

**Comment by chauthanhtra** [comment]
Mấy anh cho em hỏi có ngày dự kiến hoàn thành QĐ 130 chưa? nhiều đơn vi thắc mắc để báo cáo cho bam giám đốc

**Comment by vinh-dh** [comment]
Cập nhật mô tả QĐ 130: [Vinh - Mo ta XML Quyet Dinh 130 - 27-02-2023 (3).docx](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/Vinh%20-%20Mo%20ta%20XML%20Quyet%20Dinh%20130%20-%2027-02-2023%20(3).docx)

**Comment by vinh-dh** [comment]
Cập nhật mô tả QĐ 130: [XML130/Vinh - Mo ta XML Quyet Dinh 130 - 27-02-2023 (4).docx](https://github.com/dh-hos/Mo-ta-he-thong/commit/bbe0ecbdff65bffbdf198b30813cbc72aa78f832#diff-d27fd1e2969365128816d3d580db5136ebe0cfa67a1b389b2bc9b65820613cbc)

Thay đổi kiểu dữ liệu cột so_cccd table xml130.checkin
- Phiên bản cũ cột so_cccd kiểu dữ liệu VARCHAR(15)
- Thay đổi mới cột so_cccd kiểu dữ liệu NUMERIC(15,0)
![image](https://github.com/dh-hos/Mo-ta-he-thong/assets/112069710/d510ea36-b608-4c1e-bf5a-1b53d1612177)

**Comment by vinh-dh** [comment]
Cập nhật mô tả QĐ 130: [Vinh - Mo ta XML Quyet Dinh 130 - 27-02-2023 (5).docx](https://github.com/dh-hos/Mo-ta-he-thong/commit/3f5da89d19008bfc2fa54c7b13c897f407b5b8f5#diff-533e8a0fd0ca09403766b2adcff9675435b85761b8c506ce2be59a0ee9db1f58)

**Comment by vinh-dh** [comment]
Cập nhật mô tả QĐ 130: [Vinh - Mo ta XML Quyet Dinh 130 - 27-02-2023 (6).docx](https://github.com/dh-hos/Mo-ta-he-thong/commit/e646ec1ab5f8638930dc743f97b6d38091049465)

![image](https://github.com/dh-hos/To_Lap_Trinh/assets/112069710/a46b700b-7ba1-439d-ae2f-ee4efa74f18c)

**Comment by ongtrieuhau-dh** [comment]
Đóng lại, đã thực hiện mô tả tại đây https://github.com/dh-hos/Mo-ta-he-thong/tree/main/XML130
