### ISSUE TITLE
Yêu cầu - Mô tả thực hiện công văn 31/BHXH-GDBHYT

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/Mo-ta-he-thong#24]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **13/04/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **21/04/2023**
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) **DH Solution**

# ![yeu_cau_phat_sinh](https://img.shields.io/badge/Yêu%20cầu%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

```
```
[31-BHXH-GĐBHYT-Công văn vv mã hóa tạm thời đối với dịch vụ kỹ thuật sử dụng phương pháp vô cảm gây tê chư quy định giá.pdf](https://github.com/dh-hos/Mo-ta-he-thong/files/11217393/31-BHXH-GDBHYT-Cong.van.vv.ma.hoa.t.m.th.i.d.i.v.i.d.ch.v.k.thu.t.s.d.ng.ph.ng.phap.vo.c.m.gay.te.ch.quy.d.nh.gia.pdf)

```
```

**Comment by ongtrieuhau** [comment]
Em thực hiện mô tả tại đây nhé a [Mô tả hệ thống](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/20230415-Hau-CV1731-BHXH-G%C4%90%C4%90T-Thanh-toan-phau-thuat-vo-cam-gay-te.md)

**Comment by ongtrieuhau** [comment]
Em có thay đổi mô tả [ở đây](https://github.com/dh-hos/Mo-ta-he-thong/commit/5717ecc3c5544f52305e51d8cf6862b6db202dba) nhờ anh @nghivanbi duyệt thực hiện nhé

**Comment by nghivanbi** [comment]
OK thực hiện theo cập nhật mô tả nhé.

**Comment by ongtrieuhau-dh** [comment]
Đóng, lại ![](https://i.imgur.com/C7EOfCH.png)
