### ISSUE TITLE
Yêu cầu - Cấp mã cơ sở khám chữa bệnh mới.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/Mo-ta-he-thong#25]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-02: Mô tả thay đổi hệ thống DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU MÔ TẢ THAY ĐỔI HỆ THỐNG</h1>  
</div>

#

-  ![nguoi_lap](https://img.shields.io/badge/Người%20lập-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_lap](https://img.shields.io/badge/Ngày%20lập-:-blue?style=plastic&logo=github) **06/06/2023**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **16/06/2023**
-  ![khach_hang](https://img.shields.io/badge/Khách%20hàng-:-blue?style=plastic&logo=github) **DH Solution**

# ![yeu_cau_phat_sinh](https://img.shields.io/badge/Yêu%20cầu%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

SỞ Y TẾ TP. CẦN THƠ
**Mã BV: 92117**
BỆNH VIỆN HUYẾT HỌC - TRUYỀN MÁU CẦN THƠ
Địa chỉ: 317, Đường Nguyễn Văn Linh, Phường An Khánh, Quận Ninh Kiều, Thành phố Cần Thơ
Điện thoại: 02923898300

# ![trien_khai](https://img.shields.io/badge/Qui%20trình%20thực%20hiện%20trên%20phần%20mềm%20–%20triển%20khai-:-blue?style=for-the-badge&logo=github)

Nội dung| Thời gian | Ngày dự kiến bắt đầu
-- | -- | --
Tập huấn người dùng. | 08 ngày | 07/06/2023
Chuẩn bị dữ liệu vận hành. | 05 ngày | 19/06/2023
Cài đặt phần mềm cho các Khoa phòng. | 04 ngày | 26/06/2023
Họp giải đáp thắc mắc trước khi vận hành   phần mềm | 01 ngày | 30/06/2023
Chạy chương trình và theo dõi vận hành   thực tế | 10 ngày | 03/07/2023
Chạy chương trình và theo dõi hỗ trợ   vận hành từ xa | 09 ngày | 17/07/2023
Nghiệm thu và giao hệ thống. | 02 ngày | 28/07/2023

# ![xu_ly_yeu_cau](https://img.shields.io/badge/Xử%20lý%20yêu%20cầu-:-blue?style=for-the-badge&logo=github)

1. Thực hiện cấp License theo mã bệnh viện.
2. Fees: mở thêm kết nối hóa đơn điện tử với MISA.
3. Lab: liên kết xét nghiệm TPH.
4. Các module cập nhật License mới.

**Comment by lqbinh1987** [comment]
Mấy anh @ coi tranh thủ build lại bản mới theo yêu cầu giúp em.

**Comment by lqbinh1987** [comment]
@nghivanbi @ongtrieuhau @vinh-dh @vuongdh
Nhờ mấy anh build lại dùm em theo mã BV mới, vì có nhiều đặc thù nên em mới yêu cầu làm riêng và test được. Thanks @vuongdh

**Comment by ongtrieuhau** [comment]
Cập nhật: 

- Libraries @nghivanbi , @vuongdh , @vinh-dh : [Cập nhật Lisence 92117](https://github.com/dh-hos/oLibraries/commit/0521d639763a71301fa4c97c9b2499a463b3d120)
- Services: [3.23.0623.1](https://github.com/dh-hos/dhg.hospitalservices/commit/1fc1856898f773e7c09b590644b78cb2513e882e)
- Printer: [3.23.0623.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/b1a179190cea2f8859c11bb4ccc9cd954f051350)
- Fees: [3.23.0623.1](https://github.com/dh-hos/dhg.hospitalfees/commit/b3b069f79e5299d69b2a93f841bb907e2f35457b)
- Admin: [3.23.0623.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/f251ef449c327a4d68a1248e4f4344c88b4a54aa)

**Comment by nghivanbi** [comment]
Cập nhật:
- Register: [v3.23.0623.2](http://www.fsend.vn/download/AN3Uhs6AAaYmX1A7H-PmXMQLyuU9MI-_)

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230623](https://gofile.me/78TQg/6HW6HEd93)
- [HospitalDiagnoseSetup20230623](https://gofile.me/78TQg/Un3yivnvc)
- [HospitalLaboratorySetup20230623](https://gofile.me/78TQg/wuyg7yoSg)

**Comment by vuongdh** [comment]
[Treament 2023.06.23.v1](https://gofile.me/78TQg/MBx8AYg94)

**Comment by lqbinh1987** [comment]
Nhờ a @ongtrieuhau cấp key sử dụng HĐĐT của Misa dùm em.

**Comment by ongtrieuhau** [comment]
> Nhờ a @ongtrieuhau cấp key sử dụng HĐĐT của Misa dùm em.

Cho em cái hạn cái anh @nghivanbi

**Comment by nghivanbi** [comment]
Cấp tới 31/07/2023 nhé @ongtrieuhau

**Comment by ongtrieuhau** [comment]
Đây nhé @lqbinh1987 
{"AtRow":68,"mabvbh":"92117","DateExpires":"2023-07-31","UseHddtBy":"Misa","Trial":""}
=====DECODE=====
`U2FsdGVkX1/FMCLqovRDNpJ3IK2GyYOV9iXjq7UY8JtW9UwdnxXGfNnXWZoyDqik6h/Ssep1Gpazqr/e5VwS5qpE2XzTHtutfbZlUpGGDgbFvRgpT65ZZaTTyNCf3/gAKHcUAUSM1S+S1fdTzd0LTA==`

**Comment by vinh-dh** [comment]
Thông tin kết nối API LIS cho TPH:

- Server API: `http://192.168.1.35:8080`
- Username: `tph`
- Password: `tph`
- Thời hạn demo: `31/07/2023`
